### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by douggr** [dritc/standards#1]
Sendo um repositório **somente** de documentação, qual licença usar?

**Comment by fernandobagno** [comment]
As da Creative Commons não se aplicam, já que é só documentação?

**Comment by douggr** [comment]
Pensei na [CC-3.0](http://creativecommons.org/licenses/by-sa/3.0/).

Só não quis colocar a licença logo _de cara_ pra não parecer um ditador.

**Comment by fernandobagno** [comment]
Sitaria ela mesmo.

**Comment by douggr** [comment]
@robopets :star:

**Comment by douggr** [comment]
**Update:** http://creativecommons.org/licenses/by/4.0/

**Comment by douggr** [comment]
Com a idéia em #3, precisa também de uma licença para o código-fonte

**Comment by douggr** [comment]
- Conteúdo licenciado sob a licença [CC BY 4.0](/dritc/standards/blob/gh-pages/docs/cc-by-4.0.md)
- Código fonte licenciado sob a licença [MIT](/dritc/standards/blob/gh-pages/docs/mit.md)
